<main id="home" class="py-5 px-3">
    <h1 class="mb-5">Secured Blog</h1>

    <h2 class="mt-5">Latest posts</h2>
    <ul class="row mt-5">
        <li class="col-4 my-2">
            <article class="card">
                <header class="card-body">
                    <h3 class="h5 card-title">Post Title</h3>
                    <h4 class="h6 card-subtitle mb-2 text-body-secondary">Category Name</h4>
                </header>
                <section class="card-body">
                    <p class="card-text">Post Excerpt</p>
                    <a href="#" class="btn btn-primary">Post Link</a>
                </section>
            </article>
        </li>
        <li class="col-4 my-2">
            <article class="card">
                <header class="card-body">
                    <h3 class="h5 card-title">Post Title</h3>
                    <h4 class="h6 card-subtitle mb-2 text-body-secondary">Category Name</h4>
                </header>
                <section class="card-body">
                    <p class="card-text">Post Excerpt</p>
                    <a href="#" class="btn btn-primary">Post Link</a>
                </section>
            </article>
        </li>
        <li class="col-4 my-2">
            <article class="card">
                <header class="card-body">
                    <h3 class="h5 card-title">Post Title</h3>
                    <h4 class="h6 card-subtitle mb-2 text-body-secondary">Category Name</h4>
                </header>
                <section class="card-body">
                    <p class="card-text">Post Excerpt</p>
                    <a href="#" class="btn btn-primary">Post Link</a>
                </section>
            </article>
        </li>
        <li class="col-4 my-2">
            <article class="card">
                <header class="card-body">
                    <h3 class="h5 card-title">Post Title</h3>
                    <h4 class="h6 card-subtitle mb-2 text-body-secondary">Category Name</h4>
                </header>
                <section class="card-body">
                    <p class="card-text">Post Excerpt</p>
                    <a href="#" class="btn btn-primary">Post Link</a>
                </section>
            </article>
        </li>
    </ul>
</main>