<main id="login" class="container py-5 px-3">
    <h1 class="mb-5">Secured Blog</h1>

    <h2 class="mt-5">Login</h2>

    <form action="index.php?route=check-login" method="post">
        <input type="hidden" name="csrf-token" id="csrf-token" value="" />
        <fieldset class="my-1">
            <label for="email" class="form-label">
                Email
            </label>
            <input type="email" name="email" id="email" class="form-control"/>
        </fieldset>
        <fieldset class="my-1">
            <label for="password" class="form-label">
                Password
            </label>
            <input type="password" name="password" id="password" class="form-control" />
        </fieldset>
        <fieldset>
            <button type="submit" class="btn btn-primary">Login</button>
        </fieldset>
    </form>
</main>