<main id="register" class="container py-5 px-3">
    <h1 class="mb-5">Secured Blog</h1>

    <h2 class="mt-5">Register</h2>

    <form action="index.php?route=check-register" method="post">
        <input type="hidden" name="csrf-token" id="csrf-token" value="" />
        <fieldset class="my-1">
            <label for="username" class="form-label">
                Username
            </label>
            <input type="text" name="username" id="username" class="form-control"/>
        </fieldset>
        <fieldset class="my-1">
            <label for="email" class="form-label">
                Email
            </label>
            <input type="email" name="email" id="email" class="form-control"/>
        </fieldset>
        <fieldset class="my-1">
            <label for="password" class="form-label">
                Password
            </label>
            <input type="password" name="password" id="password" class="form-control" />
        </fieldset>
        <fieldset class="my-1">
            <label for="confirm-password" class="form-label">
                Confirm password
            </label>
            <input type="password" name="confirm-password" id="confirm-password"  class="form-control"/>
        </fieldset>
        <fieldset>
            <button type="submit" class="btn btn-primary">Register</button>
        </fieldset>
    </form>
</main>